const char* pde_text = 
"                                                              \n"
"                                                              \n"
"PPPPPPPPPPPPPPPPP   DDDDDDDDDDDDD      EEEEEEEEEEEEEEEEEEEEEE\n"
"P::::::::::::::::P  D::::::::::::DDD   E::::::::::::::::::::E\n"
"P::::::PPPPPP:::::P D:::::::::::::::DD E::::::::::::::::::::E\n"
"PP:::::P     P:::::PDDD:::::DDDDD:::::DEE::::::EEEEEEEEE::::E\n"
"  P::::P     P:::::P  D:::::D    D:::::D E:::::E       EEEEEE\n"
"  P::::P     P:::::P  D:::::D     D:::::DE:::::E             \n"
"  P::::PPPPPP:::::P   D:::::D     D:::::DE::::::EEEEEEEEEE   \n"
"  P:::::::::::::PP    D:::::D     D:::::DE:::::::::::::::E   \n"
"  P::::PPPPPPPPP      D:::::D     D:::::DE:::::::::::::::E   \n"
"  P::::P              D:::::D     D:::::DE::::::EEEEEEEEEE   \n"
"  P::::P              D:::::D     D:::::DE:::::E             \n"
"  P::::P              D:::::D    D:::::D E:::::E       EEEEEE\n"
"PP::::::PP          DDD:::::DDDDD:::::DEE::::::EEEEEEEE:::::E\n"
"P::::::::P          D:::::::::::::::DD E::::::::::::::::::::E\n"
"P::::::::P          D::::::::::::DDD   E::::::::::::::::::::E\n"
"PPPPPPPPPP          DDDDDDDDDDDDD      EEEEEEEEEEEEEEEEEEEEEE\n"
"                                                              \n"
"                                                              \n"
"                                                              \n"
"                                                              \n"
"                                                              \n"
"                                                              \n"
"                                                              \n"; // nice ascii art isn't it?